name: Build TerraformGenerator

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Grant permission to gradlew
      run: chmod +x gradlew

    - name: Build plugin with shadowJar
      run: ./gradlew buildProj:shadowJar

    - name: Upload plugin jar as artifact
      uses: actions/upload-artifact@v4
      with:
        name: TerraformGenerator
        path: buildProj/build/libs/buildProj-all.jar
